# import = ["~/.config/alacritty/themes/gruvbox-dark.toml"]

[window]
# decorations = "buttonless"
opacity = 0.82
# startup_mode = "Windowed"
title = "alacritty"

[window.padding]
x = 8
y = 8

[window.position]
x = 38
y = 112

[window.dimensions]
columns = 162
lines = 48

[cursor.style]
shape = "Block"
blinking = "On"

[cursor]
blink_interval = 456
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 15.0
normal.family = "FiraCode Nerd Font"
# normal.family = "Monaspace Neon Var"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 2

[colors]
draw_bold_text_with_bright_colors = false

[debug]
log_level = "Warn"
persistent_logging = true
print_events = false
render_timer = false

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[general]
live_config_reload = true

