live_config_reload = true
# import = ["~/.config/alacritty/themes/gruvbox-dark.toml"]

[window]
decorations = "full"
dynamic_title = true
dynamic_padding = false
opacity = 0.82
startup_mode = "Windowed"

# [window.dimensions]
# columns = 80
# lines = 35

[window.padding]
x = 8
y = 8

[cursor.style]
shape = "Block"
blinking = "On"

[cursor]
blink_interval = 456
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 2

[colors]
draw_bold_text_with_bright_colors = false

[debug]
log_level = "Warn"
persistent_logging = true
print_events = false
render_timer = false

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

